name: Build and Lint
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  PYTHON_VERSION: "3.12"
  NODE_VERSION: "20.x"

jobs:
  # Linting with ruff
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "poetry"
      - run: poetry install --only dev
      - name: Run ruff check
        run: poetry run ruff format --check .

  # Type checking with mypy
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "poetry"
      - run: poetry install
      - name: Run mypy check
        run: poetry run mypy .

  # Compile TypeScript and commit the result
  compile-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Compile TypeScript
        run: npm ci && npm run lint && npm run build
      - name: Commit and Push Compiled Files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add tarsier/tag_utils.js tarsier/tag_utils.min.js
          git commit -m "Add compiled tag_utils.js and tag_utils.min.js [skip ci]" || echo "No changes to commit"
          git push origin HEAD
